namespace SchemaSaurus.Metadata.Builders;

/// <summary>
/// Fluent builder for constructing an immutable <see cref="Sequence"/> instance,
/// typically populated from a <see cref="System.Data.Common.DbDataReader"/> row.
/// </summary>
public sealed class SequenceBuilder : IAnnotationBuilder<SequenceBuilder>
{
    private SchemaQualifiedName? _schemaQualifiedName;
    private DbType _dbType = DbType.Int64;
    private Type? _systemType;
    private long? _startValue;
    private long? _increment;
    private long? _minValue;
    private long? _maxValue;
    private bool _isCycling;
    private int? _cacheSize;
    private readonly Dictionary<string, object?> _annotations = [];

    /// <summary>Sets the schema-qualified name of the sequence.</summary>
    /// <param name="name">The schema-qualified sequence name.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    public SequenceBuilder WithQualifiedName(SchemaQualifiedName name)
    {
        _schemaQualifiedName = name;
        return this;
    }

    /// <summary>Sets the schema-qualified name from schema and sequence name strings.</summary>
    /// <param name="schema">The schema name, or <see langword="null"/> when no schema is provided.</param>
    /// <param name="name">The sequence name.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    /// <exception cref="ArgumentException">Thrown when <paramref name="name"/> is <see langword="null"/>, empty, or whitespace.</exception>
    public SequenceBuilder WithQualifiedName(string? schema, string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        _schemaQualifiedName = new SchemaQualifiedName { Schema = schema, Name = name };
        return this;
    }

    /// <summary>Sets the normalized data type of the generated values.</summary>
    /// <param name="dbType">The provider-independent database type.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    public SequenceBuilder WithDbType(DbType dbType)
    {
        _dbType = dbType;
        return this;
    }

    /// <summary>Sets the .NET CLR type this sequence maps to.</summary>
    /// <param name="systemType">The CLR <see cref="Type"/> mapped from the sequence data type.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    public SequenceBuilder WithSystemType(Type systemType)
    {
        _systemType = systemType;
        return this;
    }

    /// <summary>Sets the first value generated by the sequence.</summary>
    /// <param name="startValue">The sequence start value.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    public SequenceBuilder WithStartValue(long startValue)
    {
        _startValue = startValue;
        return this;
    }

    /// <summary>Sets the step between successive generated values.</summary>
    /// <param name="increment">The increment value.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    public SequenceBuilder WithIncrement(long increment)
    {
        _increment = increment;
        return this;
    }

    /// <summary>Sets the minimum value the sequence can generate.</summary>
    /// <param name="minValue">The minimum sequence value.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    public SequenceBuilder WithMinValue(long minValue)
    {
        _minValue = minValue;
        return this;
    }

    /// <summary>Sets the maximum value the sequence can generate.</summary>
    /// <param name="maxValue">The maximum sequence value.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    public SequenceBuilder WithMaxValue(long maxValue)
    {
        _maxValue = maxValue;
        return this;
    }

    /// <summary>Sets whether the sequence cycles back after reaching its boundary.</summary>
    /// <param name="isCycling"><see langword="true"/> if the sequence cycles; otherwise, <see langword="false"/>.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    public SequenceBuilder WithIsCycling(bool isCycling)
    {
        _isCycling = isCycling;
        return this;
    }

    /// <summary>Sets the number of values pre-allocated in memory.</summary>
    /// <param name="cacheSize">The cache size, or <see langword="null"/> to leave it unspecified.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    public SequenceBuilder WithCacheSize(int? cacheSize)
    {
        _cacheSize = cacheSize;
        return this;
    }

    /// <summary>Adds a provider-specific annotation.</summary>
    /// <param name="key">The annotation key.</param>
    /// <param name="value">The annotation value. When <see langword="null"/>, no annotation is added.</param>
    /// <returns>The current <see cref="SequenceBuilder"/> instance.</returns>
    /// <exception cref="ArgumentException">Thrown when <paramref name="key"/> is <see langword="null"/>, empty, or whitespace.</exception>
    public SequenceBuilder WithAnnotation(string key, object? value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);

        if (value is not null)
            _annotations[key] = value;

        return this;
    }

    /// <summary>
    /// Constructs the immutable <see cref="Sequence"/> instance.
    /// </summary>
    /// <returns>A fully initialized <see cref="Sequence"/>.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown when <see cref="WithQualifiedName(SchemaQualifiedName)"/> or <see cref="WithQualifiedName(string?, string)"/> has not been called.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// Thrown when <see cref="WithSystemType"/> has not been called.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// Thrown when <see cref="WithStartValue"/> has not been called.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// Thrown when <see cref="WithIncrement"/> has not been called.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// Thrown when <see cref="WithMinValue"/> has not been called.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// Thrown when <see cref="WithMaxValue"/> has not been called.
    /// </exception>
    public Sequence Build()
    {
        if (_schemaQualifiedName is null)
        {
            throw new InvalidOperationException(
                $"A schema-qualified name is required. Call {nameof(WithQualifiedName)} before {nameof(Build)}.");
        }

        if (_systemType is null)
        {
            throw new InvalidOperationException(
                $"A system type is required. Call {nameof(WithSystemType)} before {nameof(Build)}.");
        }

        if (_startValue is null)
        {
            throw new InvalidOperationException(
                $"A start value is required. Call {nameof(WithStartValue)} before {nameof(Build)}.");
        }

        if (_increment is null)
        {
            throw new InvalidOperationException(
                $"An increment is required. Call {nameof(WithIncrement)} before {nameof(Build)}.");
        }

        if (_minValue is null)
        {
            throw new InvalidOperationException(
                $"A min value is required. Call {nameof(WithMinValue)} before {nameof(Build)}.");
        }

        if (_maxValue is null)
        {
            throw new InvalidOperationException(
                $"A max value is required. Call {nameof(WithMaxValue)} before {nameof(Build)}.");
        }

        return new Sequence
        {
            QualifiedName = _schemaQualifiedName.Value,
            DbType = _dbType,
            SystemType = _systemType,
            StartValue = _startValue.Value,
            Increment = _increment.Value,
            MinValue = _minValue.Value,
            MaxValue = _maxValue.Value,
            IsCycling = _isCycling,
            CacheSize = _cacheSize,
            Annotations = _annotations,
        };
    }
}
