namespace SchemaSaurus.Metadata.Builders;

/// <summary>
/// Fluent builder for constructing an immutable <see cref="Sequence"/> instance,
/// typically populated from a <see cref="System.Data.Common.DbDataReader"/> row.
/// </summary>
public sealed class SequenceBuilder
{
    private SchemaQualifiedName? _schemaQualifiedName;
    private DbType _dbType = DbType.Int64;
    private Type? _systemType;
    private long? _startValue;
    private long? _increment;
    private long? _minValue;
    private long? _maxValue;
    private bool _isCycling;
    private int? _cacheSize;
    private readonly Dictionary<string, object?> _annotations = [];

    /// <summary>Sets the schema-qualified name of the sequence.</summary>
    public SequenceBuilder WithSchemaQualifiedName(SchemaQualifiedName name)
    {
        _schemaQualifiedName = name;
        return this;
    }

    /// <summary>Sets the schema-qualified name from schema and sequence name strings.</summary>
    public SequenceBuilder WithSchemaQualifiedName(string? schema, string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        _schemaQualifiedName = new SchemaQualifiedName { Schema = schema, Name = name };
        return this;
    }

    /// <summary>Sets the normalized data type of the generated values.</summary>
    public SequenceBuilder WithDbType(DbType dbType)
    {
        _dbType = dbType;
        return this;
    }

    /// <summary>Sets the .NET CLR type this sequence maps to.</summary>
    public SequenceBuilder WithSystemType(Type systemType)
    {
        _systemType = systemType;
        return this;
    }

    /// <summary>Sets the first value generated by the sequence.</summary>
    public SequenceBuilder WithStartValue(long startValue)
    {
        _startValue = startValue;
        return this;
    }

    /// <summary>Sets the step between successive generated values.</summary>
    public SequenceBuilder WithIncrement(long increment)
    {
        _increment = increment;
        return this;
    }

    /// <summary>Sets the minimum value the sequence can generate.</summary>
    public SequenceBuilder WithMinValue(long minValue)
    {
        _minValue = minValue;
        return this;
    }

    /// <summary>Sets the maximum value the sequence can generate.</summary>
    public SequenceBuilder WithMaxValue(long maxValue)
    {
        _maxValue = maxValue;
        return this;
    }

    /// <summary>Sets whether the sequence cycles back after reaching its boundary.</summary>
    public SequenceBuilder WithIsCycling(bool isCycling)
    {
        _isCycling = isCycling;
        return this;
    }

    /// <summary>Sets the number of values pre-allocated in memory.</summary>
    public SequenceBuilder WithCacheSize(int? cacheSize)
    {
        _cacheSize = cacheSize;
        return this;
    }

    /// <summary>Adds a provider-specific annotation.</summary>
    public SequenceBuilder WithAnnotation(string key, object? value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        _annotations[key] = value;
        return this;
    }

    /// <summary>
    /// Constructs the immutable <see cref="Sequence"/> instance.
    /// </summary>
    /// <returns>A fully initialized <see cref="Sequence"/>.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown when required properties have not been set.
    /// </exception>
    public Sequence Build()
    {
        if (_schemaQualifiedName is null)
        {
            throw new InvalidOperationException(
                $"A schema-qualified name is required. Call {nameof(WithSchemaQualifiedName)} before {nameof(Build)}.");
        }

        if (_systemType is null)
        {
            throw new InvalidOperationException(
                $"A system type is required. Call {nameof(WithSystemType)} before {nameof(Build)}.");
        }

        if (_startValue is null)
        {
            throw new InvalidOperationException(
                $"A start value is required. Call {nameof(WithStartValue)} before {nameof(Build)}.");
        }

        if (_increment is null)
        {
            throw new InvalidOperationException(
                $"An increment is required. Call {nameof(WithIncrement)} before {nameof(Build)}.");
        }

        if (_minValue is null)
        {
            throw new InvalidOperationException(
                $"A min value is required. Call {nameof(WithMinValue)} before {nameof(Build)}.");
        }

        if (_maxValue is null)
        {
            throw new InvalidOperationException(
                $"A max value is required. Call {nameof(WithMaxValue)} before {nameof(Build)}.");
        }

        return new Sequence
        {
            SchemaQualifiedName = _schemaQualifiedName.Value,
            DbType = _dbType,
            SystemType = _systemType,
            StartValue = _startValue.Value,
            Increment = _increment.Value,
            MinValue = _minValue.Value,
            MaxValue = _maxValue.Value,
            IsCycling = _isCycling,
            CacheSize = _cacheSize,
            Annotations = _annotations,
        };
    }
}
