using System.Diagnostics;

using SchemaSaurus.Metadata.Converters;

namespace SchemaSaurus.Metadata;

/// <summary>
/// Represents a database sequence object used to generate sequential numeric values.
/// </summary>
/// <remarks>
/// A sequence produces an ordered series of values defined by <see cref="StartValue"/>,
/// <see cref="Increment"/>, <see cref="MinValue"/>, and <see cref="MaxValue"/>.
/// Unlike identity columns, sequences are independent of any table and can be shared
/// across multiple tables or used in application logic.
/// </remarks>
[Equatable]
[DebuggerDisplay("{SchemaQualifiedName}")]
public sealed partial class Sequence : IAnnotatable
{
    /// <summary>
    /// Schema-qualified name that uniquely identifies this sequence within the database.
    /// </summary>
    [JsonPropertyName("schemaQualifiedName")]
    public required SchemaQualifiedName SchemaQualifiedName { get; init; }

    /// <summary>
    /// Normalized data type of the generated values.
    /// Typically <see cref="DbType.Int32"/> or <see cref="DbType.Int64"/>.
    /// Defaults to <see cref="DbType.Int64"/>.
    /// </summary>
    [JsonPropertyName("dbType")]
    public DbType DbType { get; init; } = DbType.Int64;

    /// <summary>
    /// The .NET CLR type that this sequence's values map to
    /// (e.g., <see cref="long"/> for <see cref="DbType.Int64"/>,
    /// <see cref="int"/> for <see cref="DbType.Int32"/>).
    /// Serialized as the type's <see cref="Type.FullName"/> string via
    /// <see cref="TypeJsonConverter"/>.
    /// </summary>
    [JsonPropertyName("systemType")]
    [JsonConverter(typeof(TypeJsonConverter))]
    public required Type SystemType { get; init; }

    /// <summary>
    /// The first value generated by the sequence (<c>START WITH</c>).
    /// </summary>
    [JsonPropertyName("startValue")]
    public required long StartValue { get; init; }

    /// <summary>
    /// The step between successive generated values (<c>INCREMENT BY</c>).
    /// A positive value produces an ascending sequence; a negative value produces
    /// a descending sequence.
    /// </summary>
    [JsonPropertyName("increment")]
    public required long Increment { get; init; }

    /// <summary>
    /// The minimum value the sequence can generate (<c>MINVALUE</c>).
    /// For descending sequences, this is the value at which cycling or
    /// termination occurs.
    /// </summary>
    [JsonPropertyName("minValue")]
    public required long MinValue { get; init; }

    /// <summary>
    /// The maximum value the sequence can generate (<c>MAXVALUE</c>).
    /// For ascending sequences, this is the value at which cycling or
    /// termination occurs.
    /// </summary>
    [JsonPropertyName("maxValue")]
    public required long MaxValue { get; init; }

    /// <summary>
    /// Indicates whether the sequence cycles (<c>CYCLE</c>) — wraps from
    /// <see cref="MaxValue"/> back to <see cref="MinValue"/> (or vice versa for
    /// descending sequences) instead of raising an error.
    /// Defaults to <see langword="false"/> (<c>NO CYCLE</c>).
    /// </summary>
    [JsonPropertyName("isCycling")]
    public bool IsCycling { get; init; }

    /// <summary>
    /// Number of values pre-allocated in memory to reduce I/O overhead (<c>CACHE</c>).
    /// <see langword="null"/> when the server default cache size is used.
    /// </summary>
    [JsonPropertyName("cacheSize")]
    public int? CacheSize { get; init; }

    /// <inheritdoc />
    [DictionaryEquality]
    [JsonPropertyName("annotations")]
    [JsonConverter(typeof(ReadOnlyDictionaryConverter<string, object?>))]
    public IReadOnlyDictionary<string, object?> Annotations { get; init; } = new Dictionary<string, object?>();
}
